Fixing previous Survey methods, adding new Survey update mutation
cheapreats/js-sdk pull request #6
Opened 2019-02-09 13:17 UTC by bholagabbar

2019-02-09 15:33 UTC, ralph-dev commented on src/app/controllers/SurveyController.js
> +    update(id, survey){
Is there some authentication for these update mutations? Like what happens if someone just tries to update everyone's survey but they aren't the vendor that owns it etc?

2019-02-10 16:33 UTC, junzhengca requested changes

2019-02-10 16:33 UTC, junthehacker commented on src/app/controllers/SurveyController.js
> +                mutation createSurveyResponseMutation ($survey_id: String!, $survey_response: CreateSurveyResponseInput!) {
I just realized `createSurveyResponseMutation` is not needed here, simply remove, and make it `mutation ($survey_id: ..........)`

2019-02-10 16:33 UTC, junthehacker commented on src/app/controllers/SurveyController.js
> +                mutation releaseSurveyMutation ($id: String!) {
Same goes here

2019-02-10 16:33 UTC, junthehacker commented on src/app/controllers/SurveyController.js
> +                mutation updateSurveyMutation ($id: String!, $survey: UpdateSurveyInput!) {
Same goes here.

2019-02-10 16:33 UTC, junthehacker commented on src/app/controllers/SurveyController.js
> +                mutation createSurveyMutation ($survey: CreateSurveyInput!) {
Same

2019-02-10 16:55 UTC, junzhengca approved these changes

2019-02-10 16:55 UTC, merged